window.RICHO_CATALOG = [
  ['RSP-001','AI Governance Starter Kit','Foundation'],
  ['RSP-002','Paid Pilot Readiness Kit','Foundation'],
  ['RSP-003','Buyer-Ready IP and Due-Diligence Kit','Foundation'],
  ['RSP-004','AI Use-Case Intake and Approval System','Governance, Risk & Assurance'],
  ['RSP-005','Human Authority and Escalation Framework','Governance, Risk & Assurance'],
  ['RSP-006','AI Vendor Due-Diligence Kit','Governance, Risk & Assurance'],
  ['RSP-007','AI Incident Response and Learning System','Governance, Risk & Assurance'],
  ['RSP-008','Model and Prompt Change-Control Kit','Governance, Risk & Assurance'],
  ['RSP-009','Responsible AI Evidence Pack','Governance, Risk & Assurance'],
  ['RSP-010','Data Governance Readiness Kit','Governance, Risk & Assurance'],
  ['RSP-011','Privacy-by-Design Operations Kit','Governance, Risk & Assurance'],
  ['RSP-012','Cybersecurity Evidence Readiness Kit','Governance, Risk & Assurance'],
  ['RSP-013','Regulatory Obligations Mapping Kit','Governance, Risk & Assurance'],
  ['RSP-014','Offer Architecture Builder','Commercial & Revenue'],
  ['RSP-015','Pricing and Packaging Decision Kit','Commercial & Revenue'],
  ['RSP-016','Enterprise Proposal and Quote Integrity Kit','Commercial & Revenue'],
  ['RSP-017','Sales Qualification and Deal-Control System','Commercial & Revenue'],
  ['RSP-018','Buyer Consensus and Stakeholder Mapping Kit','Commercial & Revenue'],
  ['RSP-019','Value Hypothesis and ROI Evidence Kit','Commercial & Revenue'],
  ['RSP-020','Customer Success Outcome Operating Kit','Commercial & Revenue'],
  ['RSP-021','Renewal and Expansion Readiness Kit','Commercial & Revenue'],
  ['RSP-022','Revenue Leakage and Entitlement Control Kit','Commercial & Revenue'],
  ['RSP-023','Commercial Experiment Governance Kit','Commercial & Revenue'],
  ['RSP-024','Product Requirements and Acceptance Kit','Product & Delivery'],
  ['RSP-025','Delivery Scope and Change-Control Kit','Product & Delivery'],
  ['RSP-026','Implementation Readiness Kit','Product & Delivery'],
  ['RSP-027','Service Operations and SLA Evidence Kit','Product & Delivery'],
  ['RSP-028','Quality Assurance and Release Readiness Kit','Product & Delivery'],
  ['RSP-029','Technical Debt and Refactoring Governance Kit','Product & Delivery'],
  ['RSP-030','Integration and API Readiness Kit','Product & Delivery'],
  ['RSP-031','Accessibility Readiness Kit','Product & Delivery'],
  ['RSP-032','Business Continuity and Recovery Kit','Product & Delivery'],
  ['RSP-033','Supplier and Subcontractor Assurance Kit','Product & Delivery'],
  ['RSP-034','Procurement Readiness Kit','Procurement, Market Access & Transactions'],
  ['RSP-035','RFP/RFQ Response Governance Kit','Procurement, Market Access & Transactions'],
  ['RSP-036','Vendor Registration and Due-Diligence Pack','Procurement, Market Access & Transactions'],
  ['RSP-037','Market Entry and Localisation Readiness Kit','Procurement, Market Access & Transactions'],
  ['RSP-038','Partner and Channel Governance Kit','Procurement, Market Access & Transactions'],
  ['RSP-039','Contract Obligation and Evidence Register Kit','Procurement, Market Access & Transactions'],
  ['RSP-040','Data Room Readiness Kit','Procurement, Market Access & Transactions'],
  ['RSP-041','Investment Readiness Evidence Kit','Procurement, Market Access & Transactions'],
  ['RSP-042','M&A Seller Readiness Kit','Procurement, Market Access & Transactions'],
  ['RSP-043','IP Licensing Readiness Kit','Procurement, Market Access & Transactions'],
  ['RSP-044','Executive Decision Rights System','Leadership, Workforce & Operating System'],
  ['RSP-045','Board and Governance Reporting Kit','Leadership, Workforce & Operating System'],
  ['RSP-046','Enterprise Risk and Controls Register Kit','Leadership, Workforce & Operating System'],
  ['RSP-047','Policy Lifecycle Management Kit','Leadership, Workforce & Operating System'],
  ['RSP-048','Evidence-Based Strategy Execution Kit','Leadership, Workforce & Operating System'],
  ['RSP-049','Operating Model and RACI Builder','Leadership, Workforce & Operating System'],
  ['RSP-050','Workforce AI Adoption and Change Kit','Leadership, Workforce & Operating System'],
  ['RSP-051','Training and Competency Assurance Kit','Leadership, Workforce & Operating System'],
  ['RSP-052','Knowledge Transfer and Succession Kit','Leadership, Workforce & Operating System'],
  ['RSP-053','Internal Audit and Continuous Improvement Kit','Leadership, Workforce & Operating System']
].map(([id,name,family]) => ({id,name,family}));
