const crypto=require('crypto');
class AIGovernanceControlPlane{
 constructor({store,policyEngine,eventFabric}={}){if(!store||!policyEngine)throw new Error('AIGovernanceControlPlane missing dependency');Object.assign(this,{store,policyEngine,eventFabric});}
 async registerConfiguration({agentId,provider,model,promptVersion,parameters={},environment='development',context={}}){const x=await this.store.createAIConfiguration({id:crypto.randomUUID(),agentId,provider,model,promptVersion,parameters,environment,status:'candidate',correlationId:context.correlationId});await this.#emit('ai.configuration.registered',{configurationId:x.id,agentId});return x;}
 evaluate({candidate,baseline,thresholds={}}){const limits={qualityFloor:thresholds.qualityFloor??.85,groundingFloor:thresholds.groundingFloor??.9,maxRegression:thresholds.maxRegression??.02,maxCostIncreasePct:thresholds.maxCostIncreasePct??20,maxLatencyIncreasePct:thresholds.maxLatencyIncreasePct??25};const failures=[];if(candidate.quality<limits.qualityFloor)failures.push('quality_floor');if(candidate.grounding<limits.groundingFloor)failures.push('grounding_floor');if(baseline&&candidate.quality<baseline.quality-limits.maxRegression)failures.push('quality_regression');if(baseline?.cost>0&&((candidate.cost-baseline.cost)/baseline.cost)*100>limits.maxCostIncreasePct)failures.push('cost_regression');if(baseline?.latencyMs>0&&((candidate.latencyMs-baseline.latencyMs)/baseline.latencyMs)*100>limits.maxLatencyIncreasePct)failures.push('latency_regression');if(candidate.hallucinationRate>Number(thresholds.maxHallucinationRate??.03))failures.push('hallucination_rate');return{passed:!failures.length,failures,limits,candidate,baseline};}
 async requestPromotion({configuration,evaluation,targetEnvironment='production',context={}}){if(!evaluation.passed)return{status:'blocked',reason:'evaluation_failed',evaluation};const policy=await this.policyEngine.evaluate({actor:'ai-governance',capability:'ai.configuration.promote',operation:'promote_ai_configuration',environment:targetEnvironment,risk:targetEnvironment==='production'?'high':'medium',dataClassification:'internal',context:{configurationId:configuration.id,evaluation}});if(policy.decision==='deny')return{status:'denied',policy};if(policy.decision==='require_approval'){const approval=await this.store.createApprovalRequest({sectionId:'ai-governance',agentId:'ai-governance',operation:'promote_ai_configuration',reason:policy.reason,evidence:{configuration,evaluation,targetEnvironment},correlationId:context.correlationId});return{status:'awaiting_approval',approval,policy};}return this.store.promoteAIConfiguration({configurationId:configuration.id,targetEnvironment,evaluation,correlationId:context.correlationId});}
 canaryDecision({baseline,candidate,trafficPct,thresholds={}}){const evaluation=this.evaluate({candidate,baseline,thresholds});if(!evaluation.passed)return{action:'rollback',trafficPct:0,evaluation};if(trafficPct<100)return{action:'increase_canary',trafficPct:Math.min(100,Math.max(trafficPct*2,10)),evaluation};return{action:'promote',trafficPct:100,evaluation};}
 route({configurations,requirement={}}){const eligible=configurations.filter(x=>x.status==='active'&&(!requirement.maxCost||x.cost<=requirement.maxCost)&&(!requirement.maxLatencyMs||x.latencyMs<=requirement.maxLatencyMs)&&(!requirement.minimumQuality||x.quality>=requirement.minimumQuality));return eligible.sort((a,b)=>(b.quality||0)-(a.quality||0)||((a.cost||0)-(b.cost||0)))[0]||null;}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.ai-governance',payload});}
}
module.exports={AIGovernanceControlPlane};
