class BusinessContinuityL2{
 constructor({store}={}){if(!store)throw new Error('BusinessContinuityL2 requires store');this.store=store;}
 recoveryGraph({services=[]}){const byId=new Map(services.map(s=>[s.id,s]));const ordered=[],visiting=new Set(),visited=new Set();const visit=id=>{if(visited.has(id))return;if(visiting.has(id))throw new Error('recovery_dependency_cycle');visiting.add(id);const s=byId.get(id);if(!s)throw new Error(`missing_dependency:${id}`);for(const d of s.dependsOn||[])visit(d);visiting.delete(id);visited.add(id);ordered.push(id);};services.forEach(s=>visit(s.id));return{order:ordered,services:byId};}
 backupPolicy({criticality='medium',dataClass='internal'}){const tiers={critical:{rpoMinutes:15,rtoMinutes:60,copies:3,immutable:true,restoreTestDays:7},high:{rpoMinutes:60,rtoMinutes:240,copies:3,immutable:true,restoreTestDays:14},medium:{rpoMinutes:1440,rtoMinutes:480,copies:2,immutable:false,restoreTestDays:30},low:{rpoMinutes:10080,rtoMinutes:1440,copies:1,immutable:false,restoreTestDays:90}};const p={...(tiers[criticality]||tiers.medium)};if(dataClass==='restricted'){p.immutable=true;p.copies=Math.max(3,p.copies);}return p;}
 restoreExercise({rpoMinutes,rtoMinutes,backupAgeMinutes,recoveryMinutes,integrityChecks=[]}){const integrity=integrityChecks.every(x=>x.passed);return{passed:backupAgeMinutes<=rpoMinutes&&recoveryMinutes<=rtoMinutes&&integrity,rpoMet:backupAgeMinutes<=rpoMinutes,rtoMet:recoveryMinutes<=rtoMinutes,integrity,backupAgeMinutes,recoveryMinutes};}
 failoverPlan({service,providers=[],regions=[]}){const alternatives=providers.filter(p=>p.id!==service.provider&&p.ready).sort((a,b)=>a.switchMinutes-b.switchMinutes);const regionAlternatives=regions.filter(r=>r.id!==service.region&&r.ready).sort((a,b)=>a.switchMinutes-b.switchMinutes);return{serviceId:service.id,providerFallback:alternatives[0]||null,regionFallback:regionAlternatives[0]||null,ready:!!(alternatives[0]||regionAlternatives[0])};}
 degradedMode({service,failedDependencies=[]}){const modes=service.degradedModes||[];const viable=modes.filter(m=>(m.requires||[]).every(d=>!failedDependencies.includes(d))).sort((a,b)=>(b.capabilityPct||0)-(a.capabilityPct||0));return viable[0]||{name:'offline',capabilityPct:0};}
 recoverySequence({services,failedIds=[]}){const graph=this.recoveryGraph({services});return graph.order.filter(id=>failedIds.includes(id));}
 confidence({restorePassed=false,failoverReady=false,lastExerciseDays=999,dependencyCoverage=0,runbookCoverage=0}){let score=Number(restorePassed)*30+Number(failoverReady)*25+Math.min(20,dependencyCoverage*20)+Math.min(15,runbookCoverage*15)+(lastExerciseDays<=30?10:lastExerciseDays<=90?5:0);score=Math.round(score);return{score,status:score>=90?'strong':score>=75?'good':score>=50?'weak':'critical'};}
 continuitySnapshot({services=[]}){const critical=services.filter(s=>s.criticality==='critical'&&(!s.restorePassed||!s.failoverReady));const weak=services.filter(s=>(s.confidenceScore||0)<75);return{status:critical.length?'critical':weak.length?'degraded':'healthy',criticalServices:critical.map(s=>s.id),weakServices:weak.map(s=>s.id),total:services.length};}
 async recordExercise(x){return this.store.createContinuityExercise(x);}
}
module.exports={BusinessContinuityL2};
