const crypto=require('crypto');
class BusinessContinuityDR{
 constructor({store,policyEngine,eventFabric,toolRegistry}={}){if(!store||!policyEngine)throw new Error('BusinessContinuityDR missing dependency');Object.assign(this,{store,policyEngine,eventFabric,toolRegistry});}
 async registerService({serviceId,criticality='important',rpoMinutes=60,rtoMinutes=240,degradedMode='manual',dependencies=[],context={}}){return this.store.upsertContinuityService({serviceId,criticality,rpoMinutes,rtoMinutes,degradedMode,dependencies,status:'protected',correlationId:context.correlationId});}
 async recordBackup({serviceId,backupId,createdAt=new Date().toISOString(),immutable=false,checksum,context={}}){const record=await this.store.createBackupRecord({id:backupId||crypto.randomUUID(),serviceId,createdAt,immutable,checksum,verificationStatus:'unverified',correlationId:context.correlationId});await this.#emit('continuity.backup.recorded',{serviceId,backupId:record.id});return record;}
 async verifyRestore({backup,restoreStartedAt,restoreCompletedAt,dataLossMinutes=0,checks=[],context={}}){const duration=(new Date(restoreCompletedAt)-new Date(restoreStartedAt))/60000;const service=await this.store.getContinuityService(backup.serviceId);const checksPassed=checks.every(x=>x.passed!==false);const rtoMet=duration<=service.rtoMinutes;const rpoMet=Number(dataLossMinutes)<=service.rpoMinutes;const verdict=checksPassed&&rtoMet&&rpoMet?'passed':'failed';const result=await this.store.recordRestoreVerification({backupId:backup.id,serviceId:backup.serviceId,durationMinutes:duration,dataLossMinutes,rtoMet,rpoMet,checks,verdict,correlationId:context.correlationId});await this.#emit(`continuity.restore.${verdict}`,result);return result;}
 async declareDisaster({serviceId,reason,severity='sev1',context={}}){const incident=await this.store.createDisasterEvent({id:crypto.randomUUID(),serviceId,reason,severity,status:'declared',declaredBy:context.actor||'system',correlationId:context.correlationId});await this.#emit('continuity.disaster.declared',incident);return incident;}
 async executeFailover({disaster,failoverTool,args={},context={}}){const policy=await this.policyEngine.evaluate({actor:context.actor||'continuity-ai',capability:'continuity.failover',operation:'failover',environment:context.environment||'production',risk:'high',dataClassification:'internal',context:{disasterId:disaster.id,serviceId:disaster.serviceId}});if(policy.decision==='deny')return{status:'denied',policy};if(policy.decision==='require_approval'){const approval=await this.store.createApprovalRequest({sectionId:'operations',agentId:'continuity-ai',operation:'failover',reason:policy.reason,evidence:{disaster,failoverTool,args},correlationId:context.correlationId});return{status:'awaiting_approval',approval,policy};}if(!this.toolRegistry||!failoverTool)return{status:'manual_required',reason:'no_failover_tool'};const receipt=await this.toolRegistry.invoke(failoverTool,args,{...context,disasterId:disaster.id});await this.store.recordRecoveryAction({disasterId:disaster.id,action:'failover',receipt,status:'executed',correlationId:context.correlationId});return{status:'executed',receipt};}
 assess({service,lastBackupAt,lastVerifiedRestoreAt,now=new Date()}){const backupAge=(now-new Date(lastBackupAt))/60000;const restoreAgeDays=(now-new Date(lastVerifiedRestoreAt))/86400000;const signals=[];if(backupAge>service.rpoMinutes)signals.push({code:'backup_rpo_exceeded',severity:'critical',backupAgeMinutes:backupAge});if(restoreAgeDays>Number(service.maxRestoreVerificationAgeDays||30))signals.push({code:'restore_verification_stale',severity:'warning',ageDays:restoreAgeDays});return{status:signals.some(x=>x.severity==='critical')?'critical':signals.length?'watch':'healthy',signals};}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.business-continuity',payload});}
}
module.exports={BusinessContinuityDR};
