const crypto=require('crypto');
class DataGovernancePrivacyControlPlane{
 constructor({store,policyEngine,eventFabric}={}){if(!store||!policyEngine)throw new Error('DataGovernancePrivacyControlPlane missing dependency');Object.assign(this,{store,policyEngine,eventFabric});}
 classify({fields={},declared='internal'}){const sensitiveKeys=/email|phone|address|name|customer|ip|token|secret|payment|dob|birth/i;const detected=Object.keys(fields).filter(k=>sensitiveKeys.test(k));const classification=detected.some(k=>/token|secret|payment/i.test(k))?'restricted':detected.length?'confidential':declared;return{classification,detectedFields:detected,minimise:detected.filter(k=>fields[k]==null||fields[k]==='')};}
 async registerPurpose({name,purpose,lawfulBasis,allowedData=[],retentionDays,regions=[],context={}}){if(!name||!purpose||!lawfulBasis)throw new Error('Purpose requires name, purpose and lawful basis');return this.store.createDataPurpose({id:crypto.randomUUID(),name,purpose,lawfulBasis,allowedData,retentionDays,regions,status:'active',correlationId:context.correlationId});}
 async authorizeAccess({actor,sectionId,purposeId,dataClass,operation='read',region='AU',context={}}){const purpose=await this.store.getDataPurpose(purposeId);if(!purpose||purpose.status!=='active')return{allowed:false,reason:'invalid_purpose'};if(purpose.regions?.length&&!purpose.regions.includes(region))return{allowed:false,reason:'region_not_allowed'};const policy=await this.policyEngine.evaluate({actor,capability:'data.access',operation,environment:context.environment||'development',risk:dataClass==='restricted'?'high':'medium',dataClassification:dataClass,context:{sectionId,purposeId,region}});const allowed=policy.decision==='allow';await this.store.recordDataAccess({actor,sectionId,purposeId,dataClass,operation,region,allowed,reason:policy.reason,correlationId:context.correlationId});return{allowed,reason:allowed?'purpose_and_policy_allowed':policy.reason||policy.decision,policy};}
 retentionDecision({createdAt,retentionDays,legalHold=false,now=new Date()}){if(legalHold)return{action:'retain',reason:'legal_hold'};const expires=new Date(new Date(createdAt).getTime()+Number(retentionDays)*86400000);return now>=expires?{action:'delete_or_anonymise',expiresAt:expires}:{action:'retain',expiresAt:expires};}
 async requestSubjectAction({subjectRef,type,scope={},context={}}){if(!['access','export','delete','correct','restrict'].includes(type))throw new Error('Unsupported subject action');const request=await this.store.createPrivacyRequest({id:crypto.randomUUID(),subjectRef,type,scope,status:'pending_verification',correlationId:context.correlationId});await this.#emit('privacy.request.created',{requestId:request.id,type});return request;}
 async planDeletion({subjectRef,records=[],context={}}){const actions=records.map(r=>({recordId:r.id,system:r.system,action:r.legalHold?'retain_legal_hold':r.requiredForAccounting?'restrict_and_retain':'delete_or_anonymise',reason:r.legalHold?'legal_hold':r.requiredForAccounting?'statutory_retention':'subject_request'}));return this.store.createDeletionPlan({id:crypto.randomUUID(),subjectRef,actions,status:'awaiting_approval',correlationId:context.correlationId});}
 minimise(payload={},allowedFields=[]){return Object.fromEntries(Object.entries(payload).filter(([k])=>allowedFields.includes(k)));}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.data-governance',payload});}
}
module.exports={DataGovernancePrivacyControlPlane};
