const crypto=require('crypto');

class EnterpriseMemoryGraph{
 constructor({store,policyEngine,eventFabric}={}){if(!store||!policyEngine)throw new Error('EnterpriseMemoryGraph missing dependency');Object.assign(this,{store,policyEngine,eventFabric});}
 async remember({type,externalKey,label,content,source,confidence=.8,validFrom=new Date().toISOString(),validTo=null,sensitivity='internal',visibility=['owner'],supersedes=null,tags=[],context={}}){if(!type||!label||!source)throw new Error('Memory requires type,label,source');const memory=await this.store.createEnterpriseMemory({id:crypto.randomUUID(),type,externalKey,label,content,source,confidence,validFrom,validTo,sensitivity,visibility,supersedes,tags,correlationId:context.correlationId});if(supersedes)await this.store.supersedeEnterpriseMemory({oldMemoryId:supersedes,newMemoryId:memory.id});await this.#emit('memory.created',{memoryId:memory.id,type,source});return memory;}
 async retrieve({agentId,sectionId,query,subjectType,subjectId,limit=20,context={}}){const policy=await this.policyEngine.evaluate({actor:agentId,capability:'knowledge.read',operation:'retrieve_memory',environment:context.environment||'development',risk:'low',dataClassification:context.dataClassification||'internal',context:{sectionId,subjectType,subjectId}});if(policy.decision!=='allow')return{status:policy.decision,items:[],policy};const candidates=await this.store.searchEnterpriseMemory({query,subjectType,subjectId,limit:limit*3});const now=Date.now();const filtered=candidates.filter(x=>isTemporallyValid(x,now)&&canSee(x,{agentId,sectionId})).sort(rankMemory).slice(0,limit);return{status:'ok',items:filtered,policy};}
 async connect({fromMemoryId,relation,toMemoryId,confidence=1,evidence=[]}){const edge=await this.store.createEnterpriseMemoryEdge({fromMemoryId,relation,toMemoryId,confidence,evidence});await this.#emit('memory.edge.created',{fromMemoryId,relation,toMemoryId});return edge;}
 async explain({memoryId,maxDepth=4}){const visited=new Set([memoryId]),frontier=[{id:memoryId,depth:0,path:[]}],paths=[];while(frontier.length){const current=frontier.shift();if(current.depth>=maxDepth)continue;for(const edge of await this.store.listEnterpriseMemoryEdges({fromMemoryId:current.id})){const path=[...current.path,edge];paths.push({memoryId:edge.toMemoryId,depth:current.depth+1,path});if(!visited.has(edge.toMemoryId)){visited.add(edge.toMemoryId);frontier.push({id:edge.toMemoryId,depth:current.depth+1,path});}}}return{rootMemoryId:memoryId,paths};}
 async provenance(memoryId){const memory=await this.store.getEnterpriseMemory(memoryId);if(!memory)return null;const chain=[];let current=memory;const seen=new Set();while(current&&!seen.has(current.id)){seen.add(current.id);chain.push({id:current.id,source:current.source,confidence:current.confidence,validFrom:current.validFrom,validTo:current.validTo,supersedes:current.supersedes});current=current.supersedes?await this.store.getEnterpriseMemory(current.supersedes):null;}return{memory,chain};}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.enterprise-memory-graph',payload});}
}
function isTemporallyValid(x,now){const from=x.validFrom?Date.parse(x.validFrom):0,to=x.validTo?Date.parse(x.validTo):Infinity;return from<=now&&now<=to&&!x.isSuperseded;}
function canSee(x,{agentId,sectionId}){const v=x.visibility||[];return v.includes('all')||v.includes('owner')&&agentId==='owner'||v.includes(agentId)||v.includes(sectionId);}
function rankMemory(a,b){const ac=Number(a.confidence||0),bc=Number(b.confidence||0);if(bc!==ac)return bc-ac;return Date.parse(b.validFrom||0)-Date.parse(a.validFrom||0);}
module.exports={EnterpriseMemoryGraph,isTemporallyValid,canSee};
