const crypto=require('crypto');
class L2RuntimeProfessional{
 constructor({store,clock=()=>new Date(),telemetry,eventFabric,maxConcurrency=8,maxQueueDepth=1000,defaultBudgetMs=120000}={}){if(!store)throw new Error('L2RuntimeProfessional requires store');Object.assign(this,{store,clock,telemetry,eventFabric,maxConcurrency,maxQueueDepth,defaultBudgetMs});this.circuits=new Map();}
 async admission({sectionId,agentId,operation,priority=100,requiredCapabilities=[],budgetMs=this.defaultBudgetMs,quotaKey=sectionId}){const depth=await this.store.queueDepth?.()||0;if(depth>=this.maxQueueDepth)return{allowed:false,reason:'backpressure',depth};const quota=await this.store.getRuntimeQuota?.(quotaKey);if(quota&&Number(quota.inFlight||0)>=Number(quota.maxInFlight||Infinity))return{allowed:false,reason:'quota_exceeded',quotaKey};const circuit=this.circuits.get(operation);if(circuit?.state==='open'&&new Date(circuit.retryAt)>this.clock())return{allowed:false,reason:'circuit_open',retryAt:circuit.retryAt};return{allowed:true,sectionId,agentId,operation,priority,requiredCapabilities,budgetMs,quotaKey};}
 async dispatch(job,workers=[]){const capable=workers.filter(w=>w.status==='healthy'&&job.requiredCapabilities.every(c=>(w.capabilities||[]).includes(c))&&Number(w.inFlight||0)<Number(w.maxConcurrency||1));capable.sort((a,b)=>(a.inFlight||0)-(b.inFlight||0)||(b.capacityScore||0)-(a.capacityScore||0));if(!capable.length)return{status:'queued',reason:'no_capable_worker'};const worker=capable[0];const fence=crypto.randomUUID();const lease=await this.store.claimWithFence({jobId:job.id,workerId:worker.id,fence,leaseExpiresAt:new Date(this.clock().getTime()+Number(job.leaseMs||60000))});return lease?{status:'dispatched',workerId:worker.id,fence}:{status:'queued',reason:'claim_conflict'};}
 async runPool({claim,execute,workers=1}){const width=Math.max(1,Math.min(this.maxConcurrency,workers));const slots=Array.from({length:width},async()=>{const job=await claim();if(!job)return{status:'idle'};return this.executeWithBudget(job,()=>execute(job));});return Promise.all(slots);}
 async executeWithBudget(job,fn){const budgetMs=Number(job.budgetMs||this.defaultBudgetMs);const started=this.clock();let timer;try{const result=await Promise.race([Promise.resolve().then(fn),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error('execution_budget_exceeded'),{code:'BUDGET_EXCEEDED'})),budgetMs);})]);this.recordSuccess(job.operation);await this.store.recordRuntimeMetric?.({jobId:job.id,metric:'duration_ms',value:this.clock()-started,status:'completed'});return{status:'completed',result};}catch(error){this.recordFailure(job.operation);await this.store.recordRuntimeMetric?.({jobId:job.id,metric:'failure',value:1,status:error.code==='BUDGET_EXCEEDED'?'budget_exceeded':'failed'});throw error;}finally{clearTimeout(timer);}}
 recordFailure(key,{threshold=3,cooldownMs=60000}={}){const prior=this.circuits.get(key)||{failures:0,state:'closed'};const failures=prior.failures+1;this.circuits.set(key,failures>=threshold?{failures,state:'open',retryAt:new Date(this.clock().getTime()+cooldownMs).toISOString()}:{...prior,failures});}
 recordSuccess(key){this.circuits.set(key,{failures:0,state:'closed'});}
 async detectStuck({maxRuntimeMs=300000}={}){const running=await this.store.listRunningJobs?.()||[];const now=this.clock();return running.filter(j=>now-new Date(j.startedAt)>maxRuntimeMs).map(j=>({jobId:j.id,workerId:j.leaseOwner,ageMs:now-new Date(j.startedAt),action:'reap_or_escalate'}));}
 async deadLetter(job,error){const record=await this.store.appendDeadLetter({id:crypto.randomUUID(),jobId:job.id,operation:job.operation,payloadHash:hash(job.payload),error:{name:error.name,message:error.message},replayCount:0,createdAt:this.clock().toISOString()});await this.#emit('runtime.dead_letter.created',record);return record;}
 async replayDeadLetter({deadLetterId,approvedBy}){const dl=await this.store.getDeadLetter(deadLetterId);if(!dl)throw new Error('dead letter not found');if(dl.replayCount>=Number(dl.maxReplays||3))return{status:'blocked',reason:'replay_limit'};const replay=await this.store.requeueDeadLetter({deadLetterId,approvedBy,replayedAt:this.clock()});await this.#emit('runtime.dead_letter.replayed',replay);return{status:'requeued',replay};}
 async workloadSnapshot(){const x=await this.store.runtimeSnapshot?.()||{};return{...x,circuits:[...this.circuits.entries()].map(([operation,state])=>({operation,...state})),capturedAt:this.clock().toISOString()};}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.l2-runtime',payload});}
}
function hash(v){return require('crypto').createHash('sha256').update(JSON.stringify(v||{})).digest('hex')}
module.exports={L2RuntimeProfessional};
