class ObservabilitySREL2{
 constructor({store,clock=()=>new Date()}={}){if(!store)throw new Error('ObservabilitySREL2 requires store');Object.assign(this,{store,clock});}
 async recordSpan({traceId,spanId,parentSpanId=null,service,operation,durationMs,status='ok',attributes={},context={}}){return this.store.createTraceSpan({traceId,spanId,parentSpanId,service,operation,durationMs,status,attributes,correlationId:context.correlationId,createdAt:this.clock().toISOString()});}
 serviceMap(spans=[]){const nodes=[...new Set(spans.map(s=>s.service))];const byId=new Map(spans.map(s=>[s.spanId,s]));const edges=[];for(const s of spans){const p=byId.get(s.parentSpanId);if(p&&p.service!==s.service&&!edges.some(e=>e.from===p.service&&e.to===s.service))edges.push({from:p.service,to:s.service});}return{nodes,edges};}
 sloStatus({target=.999,good,total,errorBudgetWindowMinutes=43200,elapsedMinutes=60}){const availability=total?good/total:1;const allowedBad=1-target;const actualBad=1-availability;const consumed=allowedBad?actualBad/allowedBad:0;const burnRate=elapsedMinutes?consumed/(elapsedMinutes/errorBudgetWindowMinutes):0;return{target,availability,errorBudgetConsumed:consumed,burnRate,status:availability>=target?'healthy':burnRate>=14?'critical':burnRate>=6?'high':'degraded'};}
 burnAlert({shortWindow,longWindow,thresholds={critical:14,high:6}}){const max=Math.max(shortWindow.burnRate||0,longWindow.burnRate||0);return{alert:max>=thresholds.high,severity:max>=thresholds.critical?'critical':max>=thresholds.high?'high':'none',burnRate:max};}
 anomaly({value,baselineMean,baselineStdDev=1,zThreshold=3}){const z=baselineStdDev?Math.abs(value-baselineMean)/baselineStdDev:0;return{anomalous:z>=zThreshold,zScore:z};}
 syntheticProbe({name,statusCode,latencyMs,maxLatencyMs=1500,expectedStatus=200}){const passed=statusCode===expectedStatus&&latencyMs<=maxLatencyMs;return{name,passed,statusCode,latencyMs,reason:statusCode!==expectedStatus?'unexpected_status':latencyMs>maxLatencyMs?'latency_slo':'ok'};}
 cardinalityGuard({labels={},allowedKeys=[],maxUniqueValues=100,knownValues={}}){const rejected=[];for(const [k,v] of Object.entries(labels)){if(!allowedKeys.includes(k)){rejected.push(k);continue;}const set=new Set(knownValues[k]||[]);set.add(String(v));if(set.size>maxUniqueValues)rejected.push(k);}return{allowed:!rejected.length,rejectedKeys:rejected};}
 incidentTimeline(events=[]){return[...events].sort((a,b)=>new Date(a.at)-new Date(b.at)).map((e,i)=>({...e,sequence:i+1}));}
 capacityForecast({currentUtilization,growthPerDay,days=30,limit=.8}){const projected=currentUtilization+growthPerDay*days;const daysToLimit=growthPerDay>0?Math.max(0,(limit-currentUtilization)/growthPerDay):Infinity;return{projectedUtilization:projected,daysToLimit,risk:projected>=limit?'capacity_risk':'ok'};}
 diagnose({signals=[]}){const ranked=[...signals].sort((a,b)=>(b.severityScore||0)-(a.severityScore||0));return{primary:ranked[0]||null,contributing:ranked.slice(1,4),confidence:ranked.length?Math.min(1,(ranked[0].severityScore||0)/100):0};}
 reliabilitySnapshot({slos=[],probes=[],incidentsOpen=0,capacity=[]}){const criticalSlo=slos.some(s=>s.status==='critical');const failedProbe=probes.some(p=>!p.passed);const capacityRisk=capacity.some(c=>c.risk==='capacity_risk');return{status:criticalSlo||incidentsOpen>0?'critical':failedProbe||capacityRisk?'degraded':'healthy',criticalSlo,failedProbe,capacityRisk,incidentsOpen};}
}
module.exports={ObservabilitySREL2};
