const crypto=require('crypto');
class QualityReleaseAssuranceV2{
 constructor({store,eventFabric}={}){if(!store)throw new Error('QualityReleaseAssuranceV2 requires store');Object.assign(this,{store,eventFabric});}
 async registerInvariant({name,description,severity='critical',scope='platform',checker,context={}}){return this.store.createQualityInvariant({id:crypto.randomUUID(),name,description,severity,scope,checker,status:'active',correlationId:context.correlationId});}
 assessEvidence({tests=[],contracts=[],synthetics=[],chaos=[],coverage={},flakyTests=[]}={}){const failures=[];const passedTests=tests.filter(t=>t.status==='passed').length;const totalTests=tests.length;const testPassRate=totalTests?passedTests/totalTests:0;if(totalTests&&testPassRate<1)failures.push('test_failures');if(contracts.some(c=>c.status!=='passed'))failures.push('contract_failures');if(synthetics.some(s=>s.status!=='passed'))failures.push('synthetic_failures');if(chaos.some(c=>c.severity==='critical'&&c.status!=='passed'))failures.push('critical_chaos_failure');const line=Number(coverage.line??0),branch=Number(coverage.branch??0),evidence=Number(coverage.evidence??0);if(line<.8)failures.push('line_coverage_low');if(branch<.7)failures.push('branch_coverage_low');if(evidence<.85)failures.push('evidence_coverage_low');if(flakyTests.some(f=>Number(f.flakeRate)>0.05))failures.push('flaky_tests_high');const confidence=Math.max(0,Math.min(1,(testPassRate*.25)+(Math.min(1,line)*.2)+(Math.min(1,branch)*.15)+(Math.min(1,evidence)*.25)+((contracts.every(c=>c.status==='passed')&&synthetics.every(s=>s.status==='passed'))?.15:0)));return{passed:!failures.length,failures,confidence,metrics:{testPassRate,lineCoverage:line,branchCoverage:branch,evidenceCoverage:evidence}};}
 evaluateInvariant({invariant,result}){const passed=result===true||result?.passed===true;return{invariantId:invariant.id||invariant.name,passed,severity:invariant.severity||'critical',evidence:typeof result==='object'?result:{result}};}
 async recordRun({releaseId,results,context={}}){const summary=this.assessEvidence(results);const run=await this.store.createQualityAssuranceRun({id:crypto.randomUUID(),releaseId,summary,results,correlationId:context.correlationId});await this.#emit('quality.assurance.completed',{runId:run.id,releaseId,summary});return{...run,summary};}
 releaseGate({assurance,minimumConfidence=.9}){if(!assurance?.passed)return{status:'blocked',reason:'assurance_failures',assurance};if(Number(assurance.confidence)<minimumConfidence)return{status:'blocked',reason:'confidence_below_threshold',assurance};return{status:'ready',confidence:assurance.confidence};}
 syntheticJourney({steps=[]}){const failed=steps.find(s=>s.status!=='passed');return{status:failed?'failed':'passed',completedSteps:failed?steps.indexOf(failed):steps.length,failedStep:failed?.name||null,steps};}
 detectFlakiness(history=[]){const grouped=new Map();for(const r of history){const a=grouped.get(r.test)||[];a.push(r.status);grouped.set(r.test,a);}return[...grouped].map(([test,statuses])=>{let transitions=0;for(let i=1;i<statuses.length;i++)if(statuses[i]!==statuses[i-1])transitions++;return{test,runs:statuses.length,flakeRate:statuses.length>1?transitions/(statuses.length-1):0};});}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.quality-assurance',payload});}
}
module.exports={QualityReleaseAssuranceV2};
