const crypto=require('crypto');
class ReleaseDeploymentControlPlane{
 constructor({store,policyEngine,eventFabric}={}){if(!store||!policyEngine)throw new Error('ReleaseDeploymentControlPlane missing dependency');Object.assign(this,{store,policyEngine,eventFabric});}
 async registerArtifact({version,commitSha,digest,buildId,evidence={},context={}}){if(!version||!commitSha||!digest)throw new Error('Artifact requires version, commit SHA and digest');return this.store.createReleaseArtifact({id:crypto.randomUUID(),version,commitSha,digest,buildId,evidence,immutable:true,correlationId:context.correlationId});}
 async createManifest({artifactId,environment,migrations=[],configDigest,dependencies={},strategy='canary',context={}}){return this.store.createDeploymentManifest({id:crypto.randomUUID(),artifactId,environment,migrations,configDigest,dependencies,strategy,status:'planned',correlationId:context.correlationId});}
 evaluateGates({tests={},security={},migrations={},artifact={},environment='staging'}){const failures=[];if(tests.passed!==true)failures.push('tests_failed');if(security.criticalFindings>0)failures.push('critical_security_findings');if(migrations.destructive&&!migrations.approved)failures.push('destructive_migration_unapproved');if(!artifact.digestVerified)failures.push('artifact_digest_unverified');if(environment==='production'&&!artifact.reproducible)failures.push('artifact_not_reproducible');return{passed:!failures.length,failures};}
 async requestDeployment({manifest,gates,context={}}){if(!gates.passed)return{status:'blocked',gates};const risk=manifest.environment==='production'?'high':'medium';const policy=await this.policyEngine.evaluate({actor:'release-engineering',capability:'deployment.promote',operation:'deploy_release',environment:manifest.environment,risk,dataClassification:'internal',context:{manifestId:manifest.id,strategy:manifest.strategy}});if(policy.decision==='deny')return{status:'denied',policy};if(policy.decision==='require_approval'){const approval=await this.store.createApprovalRequest({sectionId:'release-engineering',agentId:'release-ai',operation:'deploy_release',reason:policy.reason,evidence:{manifest,gates},correlationId:context.correlationId});return{status:'awaiting_approval',approval,policy};}return this.store.createDeployment({id:crypto.randomUUID(),manifestId:manifest.id,environment:manifest.environment,strategy:manifest.strategy,status:'ready',correlationId:context.correlationId});}
 canaryDecision({baseline,current,trafficPct=5,thresholds={}}){const bad=(current.errorRate??0)>(thresholds.maxErrorRate??.02)||(current.p95LatencyMs??0)>(thresholds.maxP95LatencyMs??1500)||(current.availability??1)<(thresholds.minAvailability??.995);if(bad)return{action:'rollback',nextTrafficPct:0};if(trafficPct<100)return{action:'increase',nextTrafficPct:Math.min(100,Math.max(10,trafficPct*2))};return{action:'complete',nextTrafficPct:100};}
 detectDrift({desired={},actual={}}){const keys=[...new Set([...Object.keys(desired),...Object.keys(actual)])];const differences=keys.filter(k=>JSON.stringify(desired[k])!==JSON.stringify(actual[k])).map(k=>({key:k,desired:desired[k],actual:actual[k]}));return{drifted:differences.length>0,differences};}
 async createRollbackPoint({deploymentId,artifactId,configDigest,databaseCheckpoint,context={}}){return this.store.createRollbackPoint({id:crypto.randomUUID(),deploymentId,artifactId,configDigest,databaseCheckpoint,verified:false,correlationId:context.correlationId});}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.release-control',payload});}
}
module.exports={ReleaseDeploymentControlPlane};
