const crypto=require('crypto');
class ReleaseAssuranceL2{
 constructor({store}={}){if(!store)throw new Error('ReleaseAssuranceL2 requires store');this.store=store;}
 attestBuild({artifact,source,tests,dependencies=[]}){const statement={artifactDigest:artifact.digest,commitSha:source.commitSha,repository:source.repository,builder:source.builder||'github-actions',testsDigest:tests.digest,dependencies:dependencies.map(d=>({name:d.name,version:d.version,digest:d.digest||null}))};return{...statement,attestationDigest:crypto.createHash('sha256').update(JSON.stringify(statement)).digest('hex')};}
 migrationCompatibility({migrations=[]}){const blockers=[],warnings=[];for(const m of migrations){if(m.destructive&&!m.backwardCompatible)blockers.push({id:m.id,reason:'destructive_not_backward_compatible'});else if(m.lockRisk==='high')warnings.push({id:m.id,reason:'high_lock_risk'});if(m.requiresBackfill&&!m.backfillPlan)blockers.push({id:m.id,reason:'missing_backfill_plan'});}return{compatible:!blockers.length,blockers,warnings};}
 environmentParity({desired={},target={}}){const keys=[...new Set([...Object.keys(desired),...Object.keys(target)])];const differences=keys.filter(k=>JSON.stringify(desired[k])!==JSON.stringify(target[k])).map(k=>({key:k,desired:desired[k],target:target[k]}));return{score:keys.length?Math.round(((keys.length-differences.length)/keys.length)*10000)/100:100,differences,passed:differences.length===0};}
 rolloutDecision({baseline,current,stagePct=5,thresholds={}}){const failures=[];if((current.errorRate??0)>(thresholds.maxErrorRate??.02))failures.push('error_rate');if((current.p95LatencyMs??0)>(thresholds.maxP95LatencyMs??1500))failures.push('latency');if((current.availability??1)<(thresholds.minAvailability??.995))failures.push('availability');if((current.businessKpiDropPct??0)>(thresholds.maxBusinessKpiDropPct??5))failures.push('business_kpi');return failures.length?{action:'rollback',nextStagePct:0,failures}:{action:stagePct>=100?'complete':'advance',nextStagePct:Math.min(100,Math.max(10,stagePct*2)),failures:[]};}
 releaseRisk({filesChanged=0,criticalPaths=0,migrationRisk=0,dependencyChanges=0,testConfidence=1,incidentRecent=false}){let score=Math.min(100,filesChanged*.15+criticalPaths*8+migrationRisk*25+dependencyChanges*3+(1-testConfidence)*40+(incidentRecent?15:0));score=Math.round(score);return{score,risk:score>=75?'critical':score>=50?'high':score>=25?'medium':'low'};}
 changeImpact({changed=[],dependencyGraph={}}){const impacted=new Set(changed),queue=[...changed];while(queue.length){const x=queue.shift();for(const [service,deps] of Object.entries(dependencyGraph)){if((deps||[]).includes(x)&&!impacted.has(service)){impacted.add(service);queue.push(service);}}}return{changed,impacted:[...impacted]};}
 async createEvidencePackage({version,attestation,gates,parity,risk,impact,rollout,context={}}){const payload={version,attestation,gates,parity,risk,impact,rollout,correlationId:context.correlationId};const digest=crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');return this.store.createReleaseEvidencePackage({...payload,id:crypto.randomUUID(),digest,immutable:true});}
 certify({attestation,migration,parity,risk,testsPassed,securityCritical=0,rollbackVerified=false}){const blockers=[];if(!attestation?.attestationDigest)blockers.push('missing_provenance');if(!migration.compatible)blockers.push('migration_incompatible');if(!parity.passed)blockers.push('environment_drift');if(['critical','high'].includes(risk.risk))blockers.push('release_risk_too_high');if(!testsPassed)blockers.push('tests_failed');if(securityCritical>0)blockers.push('critical_security');if(!rollbackVerified)blockers.push('rollback_unverified');return{decision:blockers.length?'NO_GO':'GO',blockers};}
}
module.exports={ReleaseAssuranceL2};
