const crypto=require('crypto');
class SecurityProfessionalL2{
 constructor({store,eventFabric,clock=()=>new Date()}={}){if(!store)throw new Error('SecurityProfessionalL2 requires store');Object.assign(this,{store,eventFabric,clock});this.failures=new Map();}
 async registerIdentity({subject,type='workload',capabilities=[],trustZone='internal',context={}}){return this.store.createSecurityIdentity({id:crypto.randomUUID(),subject,type,capabilities,trustZone,status:'active',correlationId:context.correlationId});}
 issueCapabilityToken({identity,capabilities=[],ttlSeconds=300,audience,context={}}){const allowed=capabilities.every(c=>identity.capabilities.includes(c));if(!allowed)throw new Error('capability_not_granted');const now=this.clock();return{id:crypto.randomUUID(),identityId:identity.id,audience,capabilities,issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+ttlSeconds*1000).toISOString(),correlationId:context.correlationId};}
 validateToken({token,requiredCapability,audience}){const now=this.clock();if(new Date(token.expiresAt)<=now)return{allowed:false,reason:'token_expired'};if(audience&&token.audience!==audience)return{allowed:false,reason:'audience_mismatch'};if(requiredCapability&&!token.capabilities.includes(requiredCapability))return{allowed:false,reason:'capability_missing'};return{allowed:true};}
 sessionRisk({failedAuth=0,newDevice=false,impossibleTravel=false,privileged=false,anomalyScore=0}){let score=Math.min(100,failedAuth*10+Number(newDevice)*15+Number(impossibleTravel)*45+Number(privileged)*15+Number(anomalyScore)*40);return{score,risk:score>=75?'critical':score>=50?'high':score>=25?'medium':'low',stepUpRequired:privileged||score>=50,isolate:score>=80};}
 privilegedAction({session,stepUpVerified=false,capabilityVerified=false}){if(session.isolate)return{allowed:false,action:'isolate'};if(!capabilityVerified)return{allowed:false,action:'deny_capability'};if(session.stepUpRequired&&!stepUpVerified)return{allowed:false,action:'require_step_up'};return{allowed:true,action:'allow'};}
 secretRotation({lastRotatedAt,maxAgeDays=30,now=this.clock()}){const age=(now-new Date(lastRotatedAt))/86400000;return{ageDays:age,rotationRequired:age>=maxAgeDays,overdueDays:Math.max(0,age-maxAgeDays)};}
 trustDecision({sourceZone,targetZone,dataClass='internal'}){const rank={public:0,external:1,internal:2,privileged:3};const crossing=(rank[sourceZone]??0)<(rank[targetZone]??0);const restricted=dataClass==='restricted';return{allowed:!(crossing&&restricted),requiresGateway:crossing,reason:crossing&&restricted?'restricted_cross_zone':'allowed'};}
 async recordSecurityEvent({type,actor,payload={},previousHash='',context={}}){const canonical=JSON.stringify({type,actor,payload,previousHash});const hash=crypto.createHash('sha256').update(canonical).digest('hex');const event=await this.store.createSecurityEvent({id:crypto.randomUUID(),type,actor,payload,previousHash,hash,correlationId:context.correlationId});await this.#emit('security.event.recorded',{eventId:event.id,type,hash});return event;}
 verifyEventChain(events=[]){let previous='';for(const e of events){if(e.previousHash!==previous)return{valid:false,failedEventId:e.id};const canonical=JSON.stringify({type:e.type,actor:e.actor,payload:e.payload,previousHash:e.previousHash});const hash=crypto.createHash('sha256').update(canonical).digest('hex');if(hash!==e.hash)return{valid:false,failedEventId:e.id};previous=e.hash;}return{valid:true,headHash:previous};}
 posture({criticalFindings=0,highFindings=0,staleSecrets=0,untrustedDependencies=0,coverage=.9,identityCoverage=.9}){let score=100-criticalFindings*35-highFindings*10-staleSecrets*5-untrustedDependencies*8-(1-coverage)*20-(1-identityCoverage)*20;score=Math.max(0,Math.round(score));return{score,status:criticalFindings?'critical':score>=90?'strong':score>=75?'acceptable':score>=50?'weak':'critical'};}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.security-l2',payload});}
}
module.exports={SecurityProfessionalL2};
