const crypto=require('crypto');
class ThirdPartyRiskEngine{
 constructor({store,eventFabric}={}){if(!store)throw new Error('ThirdPartyRiskEngine requires store');Object.assign(this,{store,eventFabric});}
 async registerDependency({name,category,criticality='medium',provider,services=[],sla={},security={},alternatives=[],version={},dataAccess=[],context={}}){const dep=await this.store.createThirdPartyDependency({id:crypto.randomUUID(),name,category,criticality,provider,services,sla,security,alternatives,version,dataAccess,status:'active',correlationId:context.correlationId});await this.#emit('third_party.registered',{dependencyId:dep.id,name});return dep;}
 assess(dep={}){let score=0;const findings=[];const add=(pts,code,severity='warning')=>{score+=pts;findings.push({code,severity});};if(dep.criticality==='critical')add(20,'critical_dependency','info');if(!dep.alternatives?.length)add(20,'no_replacement_option','critical');if((dep.sla?.availability??1)<.995)add(10,'weak_availability_sla');if(dep.security?.status==='unknown')add(15,'security_posture_unknown','critical');if(dep.security?.lastReviewDaysAgo>180)add(10,'security_review_stale');if(dep.version?.endOfSupport===true)add(20,'version_end_of_support','critical');if(dep.concentrationPct>50)add(15,'provider_concentration_high');if(dep.dataAccess?.includes('restricted'))add(10,'restricted_data_exposure');if(dep.recovery?.tested!==true)add(10,'recovery_not_tested');return{score:Math.min(100,score),level:score>=60?'critical':score>=35?'high':score>=15?'medium':'low',findings};}
 outageImpact({dependency,affectedServices=[],durationMinutes=0}){const critical=dependency.criticality==='critical';const severity=critical&&durationMinutes>=30?'sev1':critical?'sev2':durationMinutes>=60?'sev2':'sev3';return{severity,affectedServices,durationMinutes,recommendedMode:dependency.degradedMode||'manual_review',customerImpact:critical?'likely':'possible'};}
 replacementReadiness(dep={}){const options=(dep.alternatives||[]).map(x=>({provider:x.provider||x.name,ready:Boolean(x.ready),estimatedSwitchHours:Number(x.estimatedSwitchHours||0),dataCompatibility:x.dataCompatibility||'unknown'}));const ready=options.filter(x=>x.ready);return{ready:ready.length>0,options,best:ready.sort((a,b)=>a.estimatedSwitchHours-b.estimatedSwitchHours)[0]||null};}
 versionRisk({currentVersion,latestSupportedVersion,endOfSupportAt,knownVulnerabilities=0,now=new Date()}){const eos=endOfSupportAt?new Date(endOfSupportAt):null;const expired=eos&&now>=eos;const findings=[];if(expired)findings.push('end_of_support');if(knownVulnerabilities>0)findings.push('known_vulnerabilities');if(currentVersion!==latestSupportedVersion)findings.push('not_latest_supported');return{risky:findings.length>0,findings,expired,knownVulnerabilities};}
 async snapshot({dependencyId,assessment,telemetry={},context={}}){const snap=await this.store.createThirdPartyRiskSnapshot({id:crypto.randomUUID(),dependencyId,assessment,telemetry,correlationId:context.correlationId});if(assessment.level==='critical')await this.#emit('third_party.risk.critical',{dependencyId,snapshotId:snap.id,assessment});return snap;}
 portfolioRisk(dependencies=[]){const assessed=dependencies.map(d=>({...d,risk:this.assess(d)}));const critical=assessed.filter(x=>x.risk.level==='critical');const byProvider={};for(const d of assessed){const p=d.provider||'unknown';byProvider[p]=(byProvider[p]||0)+1;}return{dependencies:assessed,total:assessed.length,criticalCount:critical.length,providerConcentration:byProvider,status:critical.length?'critical':assessed.some(x=>x.risk.level==='high')?'watch':'healthy'};}
 async #emit(type,payload){if(this.eventFabric?.publish)await this.eventFabric.publish({type,source:'richo.third-party-risk',payload});}
}
module.exports={ThirdPartyRiskEngine};
